feat(mobile): add mobile section
platanus/la-guia pull request #176
Opened 2020-09-04 18:58 UTC by DiegoAndai

Agrega una primera versión de desarrollo movil con React Native. Más que la estructura propuesta para las secciones (Porque?, Como?, ...) seguí la estructura de la sección de Ruby y Rails.

Closes #132

2020-09-04 19:10 UTC, rjherrera reviewed
Me gusta como queda! quizás pa más adelante podríamos pensar en ejemplos tipo de pantallas o algo así.

2020-09-04 19:10 UTC, rjherrera commented on setup/proyectos/expo.md
> +    npm install expo-cli --global
en estas partes podríai ponerle los `` para que se note que es código, o incluso un ```bash.

2020-09-04 19:21 UTC, DiegoAndai commented on setup/proyectos/expo.md
> +    npm install expo-cli --global
Listo 🚀

2020-09-04 21:13 UTC, difernandez requested changes
bueena está bacán! Me gusta no haber seguido la estructura, mobile es un tema más grande que amerita su propia estructura de folders yo creo jaja. Dejé un par de typos y comentarios.

Y un detalle más, recuerdo que cuando estaba desarrollando usando la app de expo y quería probar algo que requería conexión a un servidor corriendo en local tenía que hacer un bind del host a 0.0.0.0, en rails creo que es con `rails s -b 0.0.0.0`. No sé si a ti te a tocado, pero me tinca que estaría bueno mencionarlo, quizás en la parte de setup

2020-09-04 21:13 UTC, difernandez commented on stack/mobile/redux.md
> +* [Redux toolkit](https://redux-toolkit.js.org/): "redux con las baterias incluidas", este paquete incluye varias funciones para agilizar el desarrollo con Redux. Incluye funcionalidades que cumplen
- *acción
- En la palabra "slices" estaría bueno agregar este link: https://redux-toolkit.js.org/usage/usage-guide#creating-slices-of-state. Es como un concepto "nuevo" si no cachas el toolkit

2020-09-04 21:13 UTC, difernandez commented on stack/mobile/styling.md
> +* [Styled Components](https://styled-components.com/docs/basics#react-native): librería muy utilizada en React y que puede ser utilizada también en React Native. Los estilos se escriben en un multi-l
Hace tiempo vi esto: https://github.com/vadimdemedes/tailwind-rn 👀  (quizás tu lo compartiste no recuerdo jaja). No tiene sentido ponerlo acá si no es muy común y no lo hemos usado, pero estaría bueno probarlo en algún proyecto

2020-09-04 21:13 UTC, difernandez commented on stack/mobile/resources.md
> +* [React Native Directory](https://reactnative.directory/?search=highlight): repositorio de recursos para React Native
el `?search=highlight` es para mostrar de ejemplo al tiro o se pasó?

2020-09-07 21:54 UTC, DiegoAndai commented on stack/mobile/styling.md
> +* [Styled Components](https://styled-components.com/docs/basics#react-native): librería muy utilizada en React y que puede ser utilizada también en React Native. Los estilos se escriben en un multi-l
René la esta probando en Buda, va bien pero me dijo que "prevee complicaciones" en el futuo 👀 la iba a poner pero esta muy en pañales y no esta en ningún proyecto Platanus. Definitivamente tenemos que probarla a ver si vale la pena.

2020-09-08 12:34 UTC, DiegoAndai commented on stack/mobile/resources.md
> +* [React Native Directory](https://reactnative.directory/?search=highlight): repositorio de recursos para React Native
Se paso 🙊

2020-09-08 12:38 UTC, difernandez commented on stack/mobile/styling.md
> +* [Styled Components](https://styled-components.com/docs/basics#react-native): librería muy utilizada en React y que puede ser utilizada también en React Native. Los estilos se escriben en un multi-l
buena que choro, no cachaba que se estaba probando en Buda. Ahí la probamos más adelante

2020-09-08 12:42 UTC, difernandez requested changes

2020-09-08 12:42 UTC, difernandez commented on setup/proyectos/expo.md
> +Si vas a empezar a trabajar en un proy+ecto que alguien ya creó.
Se pasó un + 👀

2020-09-08 12:47 UTC, difernandez approved these changes

2020-09-08 12:48 UTC, merged