Feat/observer documentation
platanus/la-guia pull request #221
Opened 2022-03-06 20:42 UTC by fprebolledo

Se agrega la documentación de observers, para que sirven, como se usan, como testear, etc.

2022-03-14 14:42 UTC, ldlsegovia requested changes
Te comenté algunas cuestiones que tienen que ver más que nada con el orden de los enunciados para que se entienda mejor. Me cuentas que te parece :)

2022-03-14 14:42 UTC, ldlsegovia commented on stack/ruby/rails/rspec.md
> +      product.update!(current_stock: 0)
ojo que está línea tendría que ir en un before o dentro del it

2022-03-21 14:32 UTC, ldlsegovia reviewed
Unas cositas más :)

2022-03-21 14:32 UTC, ldlsegovia commented on stack/ruby/rails/powertypes.md
> +Como pueden ver las dos formas son equivalente. Entonces ¿Por qué usar observers?
falta la s en equivalente"s"

2022-03-21 14:32 UTC, ldlsegovia commented on stack/ruby/rails/powertypes.md
> +Por un lado en los callbacks va todo lo necesario para mantener la integridad del objeto, por ejemplo, el formateo de un rut. Si guardamos un objeto sin formato de rut y todos los demás están formate
Quizás mejor decir: "ese modelo" más que el dato. El que queda en un estado inválido es el modelo.

2022-03-21 14:32 UTC, ldlsegovia commented on stack/ruby/rails/rspec.md
> +2. Y que además tenemos un observer que cada vez que se guarda el objeto revisa el el stock está en 0 para marcar el producto como vendido.
"el el"

2022-03-21 14:32 UTC, ldlsegovia commented on stack/ruby/rails/rspec.md
> +      def valid
ojo acá que el método debería ser `mark_as_sold_out`.

2022-03-21 14:32 UTC, ldlsegovia commented on stack/ruby/rails/rspec.md
> +          object.status = :sold_out
En vez de hacer que `object.status = :sold_out` quizás mejor hacer el ejemplo con el envío de un mail? Pasa que en este ejemplo, estás modificando el estado del propio objeto. Algo que parece indicar que podría ir en un callback. El caso del mail es más claro me parece.

2022-03-21 14:32 UTC, ldlsegovia commented on stack/ruby/rails/rspec.md
> +    before do
Ojo que let que quedó dentro del before

```ruby
let(:product) { create(:product) }
    
before do 
  product.update!(current_stock: 0)
end
```

2022-03-21 14:32 UTC, ldlsegovia commented on stack/ruby/rails/rspec.md
> +      def valid?
`valid?` es un método que ya existe en en active record. Quizás mejor cambiarlo por `valid_stock?`

2022-03-21 14:32 UTC, ldlsegovia commented on stack/ruby/rails/rspec.md
> +      let(:product) { create(:product) }
ojo los let acá también.

2022-03-25 14:02 UTC, fprebolledo commented on stack/ruby/rails/rspec.md
> +          object.status = :sold_out
aaah si, toda la razón

2022-03-25 16:12 UTC, ldlsegovia approved these changes
👏🏻

2022-03-25 17:00 UTC, merged